### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MBach** [mauricevancooten/react-anchor-link-smooth-scroll#18]
Hi,

This module doesn't seem to work with latest React release.

https://codesandbox.io/s/00y5y25z6l

**Comment by mauricevancooten** [comment]
Thanks for letting me know.

**Comment by mauricevancooten** [comment]
Tested with React v16.7.0 and appears to be working fine.

**Comment by MBach** [comment]
Are you sure @mauricevancooten?
Did I do something wrong on my example on codesandbox?

**Comment by Pustur** [comment]
@MBach You might have figured it out by yourself in the meantime, but for posterity I'm going to let you know that there's nothing wrong with your codesandbox. 

The problem seems to be that the browser window used by codesandbox doesn't support this type of scrolling. In fact if you take the url (https://00y5y25z6l.codesandbox.io) and open it in a browser it works fine.
